# Generated by Django 3.1.7 on 2021-04-08 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=50, verbose_name='Название коллекции')),
                ('collection_description', models.TextField(verbose_name='Описание коллекции')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
            },
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exhibition_name', models.CharField(max_length=50, verbose_name='Название выставки')),
                ('date', models.DateTimeField(verbose_name='Дата выставки')),
                ('duration', models.DateTimeField(verbose_name='Дата окончания')),
                ('coverage', models.IntegerField(verbose_name='Количество человек')),
            ],
            options={
                'verbose_name': 'Выставка',
                'verbose_name_plural': 'Выставки',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=50, verbose_name='')),
                ('work_description', models.TextField(verbose_name='')),
                ('work_artist', models.CharField(max_length=50, verbose_name='')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.collection')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exhibition')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
        migrations.CreateModel(
            name='WorkPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_source', models.ImageField(upload_to='images/', verbose_name='Путь к изображению')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.work')),
            ],
            options={
                'verbose_name': 'Изображение работы',
                'verbose_name_plural': 'Изображения работ',
            },
        ),
    ]
