# Generated by Django 3.1.7 on 2021-04-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210413_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpicture',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
