# Generated by Django 3.0.7 on 2021-04-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_workpicture_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='work_views',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_artist',
            field=models.CharField(max_length=50, verbose_name='Художник'),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_description',
            field=models.TextField(verbose_name='Описание работы'),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_name',
            field=models.CharField(max_length=50, verbose_name='Название работы'),
        ),
    ]
