# Generated by Django 3.1.7 on 2021-04-30 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210425_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 30, 16, 40, 4, 464206), verbose_name='Дата создания'),
        ),
    ]
