# Generated by Django 3.1.7 on 2021-05-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210430_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collection_views',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
