# Generated by Django 3.1.7 on 2021-05-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_collection_collection_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collection_picture',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Путь к изображению'),
        ),
    ]
